version: '2.4'

services:

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: andrei
      POSTGRES_PASSWORD: password1234
      POSTGRES_DB: ecommerceapp-backend
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  ecommerceapp-keycloak:
    image: bitnami/keycloak:21.1.2
    container_name: keycloak
    restart: unless-stopped
    environment:
      - KEYCLOAK_CREATE_ADMIN_USER=true
      - KEYCLOAK_ADMIN_USER=andrei
      - KEYCLOAK_ADMIN_PASSWORD=orderia!
      - KEYCLOAK_MANAGEMENT_USER=andrei
      - KEYCLOAK_MANAGEMENT_PASSWORD=orderia!
      - KEYCLOAK_HOSTNAME=localhost
      - KEYCLOAK_HTTP_PORT=8080
      - KEYCLOAK_ENABLE_HTTPS=false
      - KEYCLOAK_BIND_ADDRESS=0.0.0.0
      - KEYCLOAK_DATABASE_HOST=ecommerceapp-keycloak-db
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_USER=keycloak
      - KEYCLOAK_DATABASE_PASSWORD=orderia!
      - KEYCLOAK_DATABASE_SCHEMA=public
    networks:
      ecommerceappnet:
    depends_on:
      - ecommerceapp-keycloak-db
    ports:
      - "80:8080"
    platform: linux/arm64

  ecommerceapp-keycloak-db:
    image: postgres:15.1
    container_name: ecommerceapp-keycloak-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=keycloak
      - POSTGRES_PASSWORD=orderia!
    volumes:
      - keycloak-db:/var/lib/postgresql/data
    networks:
      ecommerceappnet:
    ports:
      - "15431:5432"

networks:
  ecommerceappnet:

volumes:
  keycloak-db:
  pgdata: